"""
Artifact management for RLM Agent.

Handles artifact scanning, registration, and validation against expected outputs.
"""

from pathlib import Path
from typing import TYPE_CHECKING

from src.core.logger import logger

if TYPE_CHECKING:
    from src.core.run_context import RunContext


class AgentArtifacts:
    """Manages artifact tracking and validation for the agent."""

    def __init__(self, run_context: "RunContext | None" = None):
        """
        Initialize artifact manager.

        Args:
            run_context: Optional run context for artifact registration
        """
        self.run_context = run_context

    def get_artifacts(self) -> list[dict]:
        """
        Return the list of tracked artifacts for this run.

        Returns:
            List of artifact dictionaries, or empty list if no run_context
        """
        if not self.run_context:
            return []
        return list(self.run_context.artifacts)

    def scan_and_register(self) -> None:
        """
        Scan the run's artifacts directory and register any new files.

        This is called after code execution so files generated by executed
        code are discoverable via the run context and `get_artifacts()`.

        Automatically infers artifact type based on file extension:
        - Images: .png, .jpg, .jpeg, .gif, .svg
        - Data: .csv, .xlsx, .xls, .parquet, .json
        - Reports: .md, .txt, .html
        - Other: generic "file" type
        """
        if not self.run_context:
            return

        artifacts_dir = Path(self.run_context.artifacts_dir)
        if not artifacts_dir.exists():
            return

        for path in artifacts_dir.rglob("*"):
            if not path.is_file():
                continue

            filename = path.name
            # Avoid duplicate registrations
            if any(a.get("filename") == filename for a in self.run_context.artifacts):
                continue

            # Infer type from extension
            ext = path.suffix.lower()
            if ext in (".png", ".jpg", ".jpeg", ".gif", ".svg"):
                atype = "image"
            elif ext in (".csv", ".xlsx", ".xls", ".parquet", ".json"):
                atype = "data"
            elif ext in (".md", ".txt", ".html"):
                atype = "report"
            else:
                atype = "file"

            # Register with a generic description
            try:
                self.run_context.register_artifact(
                    filename,
                    artifact_type=atype,
                    description="Auto-registered"
                )
            except Exception:
                # Be tolerant: registration failure should not stop the agent
                logger.exception("Failed to register artifact %s", filename)

    def check_expected_artifacts(self, expected: list[str]) -> list[str]:
        """
        Check which expected artifacts are missing.

        Args:
            expected: List of expected artifact filenames

        Returns:
            List of missing filenames
        """
        existing = [a.get("filename", "") for a in self.get_artifacts()]
        missing = [f for f in expected if f not in existing]
        logger.debug(
            "Checking expected artifacts: existing=%s, expected=%s, missing=%s",
            existing, expected, missing
        )
        return missing
